# Example override file. Copy as docker-compose.override.yml and edit as needed

services:

  web:
    env_file: !override
      - ./config/prod.env
      - ./config/my.env # Only add the variables that you have changed
      
  nginx:
    volumes: !override
      - ./config/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - static:/wger/static:ro
      - media:/wger/media:ro
    ports: !override
      - "8888:80"

